version: '3.8'

services:
  backend:
    build: ./backend
    container_name: news-summarizer-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: news-summarizer-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    restart: always